language: go

go:
  - 1.6

sudo: required

services:
  - docker
  
script:
  - travis_wait 60 make quick-release
  
# blocklist
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
#  - master
#  - stable
  - cuericlee-patch-1
